#!/bin/bash

IconHigh="Bat[♦]:"     #good
IconMid="Bat[*]:"      #mid
IconLow="Bat[!]:"      #low
#Icon="Bat:"

Battery=$(cat /sys/class/power_supply/BAT0/capacity)
Middle="60"
Low="20"

if [ $(systemd-ac-power -v) == "yes" ]; then
  Battery="(⚡)$Battery"
fi

if [ "$Battery" -le "$Low" ]; then
		echo "$IconLow $Battery%"
elif [ "$Battery" -le "$Middle" ]; then
		echo "$IconMid $Battery%"
else
		echo "$IconHigh $Battery%"
fi
