#!/bin/bash

#Icon1=""      #good
#Icon2=""      #mid
#Icon3=""      #low
Icon="Bat:"

Battery=$(cat /sys/class/power_supply/BAT0/capacity)
Midle="70"
Low="20"

if [ "$Battery" -le "$Low" ] ; then
        echo "$Icon $Battery%"
elif [ "$Battery" -le "$Midle" ] ; then
        echo "$Icon $Battery%"
else
        echo "$Icon $Battery%"
fi
