#!/bin/bash

Icon="Vol:"

if [ $(amixer get Master | grep Left | awk '/off/ {print $6}') == "[off]" ]; then
  Volume="Muted"
else
  Volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{ print $2*100"%" }')
fi

echo "$Icon $Volume"
